import 'dart:math';

enum Suit { clubs, diamonds, hearts, spades }
enum Rank { ace, two, three, four, five, six, seven, eight, nine, ten, jack, queen, king }
class PlayingCard { final Suit suit; final Rank rank; const PlayingCard(this.suit, this.rank); bool get red => suit == Suit.diamonds || suit == Suit.hearts; String get symbol => const {Suit.clubs:'♣',Suit.diamonds:'♦',Suit.hearts:'♥',Suit.spades:'♠'}[suit]!; String get label => '${const ['A','2','3','4','5','6','7','8','9','10','J','Q','K'][rank.index]}$symbol'; String get assetRank => const ['A','2','3','4','5','6','7','8','9','10','J','Q','K'][rank.index]; }
class Deck { final List<PlayingCard> cards=[for(final s in Suit.values) for(final r in Rank.values) PlayingCard(s,r)]; void shuffle([Random? random])=>cards.shuffle(random??Random()); PlayingCard draw()=>cards.removeLast(); }
class PokerRound { final Deck deck=Deck(); final List<PlayingCard> community=[],player=[],bot=[]; PokerRound(){deck.shuffle();} void deal(){deck.cards..clear()..addAll([for(final s in Suit.values) for(final r in Rank.values) PlayingCard(s,r)]);deck.shuffle();player.clear();bot.clear();community.clear();player.addAll([deck.draw(),deck.draw()]);bot.addAll([deck.draw(),deck.draw()]);community.addAll([deck.draw(),deck.draw(),deck.draw()]);} void turn()=>community.add(deck.draw()); void river()=>community.add(deck.draw()); }
class BlackjackRound { final Deck deck=Deck(); final List<PlayingCard> player=[],dealer=[]; BlackjackRound(){deck.shuffle();} void deal(){deck.cards..clear()..addAll([for(final s in Suit.values) for(final r in Rank.values) PlayingCard(s,r)]);deck.shuffle();player.clear();dealer.clear();player.addAll([deck.draw(),deck.draw()]);dealer.addAll([deck.draw(),deck.draw()]);} static int value(List<PlayingCard> cards){var total=0,aces=0;for(final c in cards){if(c.rank==Rank.ace){total+=11;aces++;}else if(c.rank.index>=Rank.jack.index)total+=10;else total+=c.rank.index+1;}while(total>21&&aces-->0)total-=10;return total;} }
class ClassicCardGames { static const games=['Texas Hold’em Poker','Blackjack','Klondike Solitaire','FreeCell','Hearts','Spades','Crazy Eights','War']; }
