<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><OutputType>WinExe</OutputType><TargetFrameworks>net48;net6.0-windows</TargetFrameworks><UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>BizXtreme.Desktop</AssemblyName><RootNamespace>BizXtreme.Desktop</RootNamespace><Platforms>x64</Platforms></PropertyGroup>
<PropertyGroup Condition="'$(TargetFramework)'=='net6.0-windows'"><RuntimeIdentifier>win-x64</RuntimeIdentifier><SelfContained>true</SelfContained><PublishSingleFile>true</PublishSingleFile></PropertyGroup>
</Project>
