name: Build all applications
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build all
        run: bash ./build.sh
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build all
        shell: pwsh
        run: ./build.cmd
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build all
        run: bash ./build.sh
